cloud:
  cinder:
    ethereum:
      endpoint:
        url: https://fullnode.fundrequest.io
        local-url: https://mainnet.infura.io
    queue:
      block-added: cindercloud_mainnet
      user-token-import: mainnet_user_token_import